//timer.countdown,timer,timer.semver,timer.stopwatch,tests.countdown,tests.countdown2,tests.stopwatch
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import std.stdio;
import unit_threaded;

int main(string[] args)
{
    writeln("\nAutomatically generated file tests/app.d");
    writeln(`Running unit tests from dirs ["."]`);
    return runTests!(
                     "timer.countdown",
                     "timer",
                     "timer.semver",
                     "timer.stopwatch",
                     "tests.countdown",
                     "tests.countdown2",
                     "tests.stopwatch"
                     )
                     (args);
}
